### ISSUE TITLE
Curl is not installed

### ISSUE THREAD

**Issue by ghost** [mediabots/Linux-to-Windows-with-QEMU#18]
Provider: Nocix
So it's not an really an issue but more like suggestion. Some providers like mentioned Nocix doesn't install curl automatically, and as I see the script assumes you have it installed. Could you add command to install curl for you? It's kinda annoying to install it manually.

**Comment by z0mbyHG** [comment]
why don´t you add it yourself after you get the script 
just add it in the first piece of code with nano or vim 
if [ $dist = "CentOS" ] ; then
	printf "Y\n" | yum install sudo -y
	sudo yum install wget vim curl genisoimage -y
	# Downloading Portable QEMU-KVM
	echo "Downloading QEMU"
	sudo yum update -y
        sudo yum install curl # Download curl <===========
	sudo yum install -y qemu-kvm
elif [ $dist = "Ubuntu" -o $dist = "Debian" ] ; then
	printf "Y\n" | apt-get install sudo -y
	sudo apt-get install vim curl genisoimage -y
	# Downloading Portable QEMU-KVM
	echo "Downloading QEMU"
	sudo apt-get update
        sudo apt-get install curl # Download curl <==============
	sudo apt-get install -y qemu-kvm
fi

**Comment by Shazyy** [comment]
I am aware, it's just a little suggestion for less advanced users :)

**Comment by mediabots** [comment]
Ok
Thanks OP for the suggestion.
I would try to update it, next update.
