### ISSUE TITLE
Run without hardware virtualization/KVM?

### ISSUE THREAD

**Issue by ciacnorris** [mediabots/Linux-to-Windows-with-QEMU#23]
Hi, is it possible to make the script work when no hardware virtualization is available? I read QEMU can be run without KVM.
If yes, how should I modify the script?

**Comment by mediabots** [comment]
Hello
Could you forward the article, from where did you know, KVM could be run without virtulization?
  
>Воскресенье, 31 мая 2020, 16:00 +03:00 от ciacnorris <notifications@github.com>:
> 
> 
>Hi, is it possible to make the script work when no hardware virtualization is available? I read QEMU can be run without KVM.
>If yes, how should I modify the script?
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Media Bots

**Comment by mediabots** [comment]
closing, since no response from the OP
