### ISSUE TITLE
Could you please share enableRDP.ps1 file

### ISSUE THREAD

**Issue by ul0lw** [mediabots/Linux-to-Windows-with-QEMU#25]
I have installed everything but I am having problem with enableRDP.ps1
I did it in slightly different way that's why I don't have this file 
Could you please share enableRDP.ps1 file ?
Thank you
Regards,

**Comment by mediabots** [comment]
That .ps1 file is basically consist of these three PowerShell commands:
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\' -Name "fDenyTSConnections" -Value 0
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\' -Name "UserAuthentication" -Value 1
Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
 
run them one after another in the the given order.
PS- In youtube there are several videos to Enable RDP(without any commands).
 

  
>Четверг, 23 июля 2020, 9:04 +03:00 от ul0lw <notifications@github.com>:
> 
> 
>I have installed everything but I am having problem with enableRDP.ps1
>I did it in slightly different way that's why I don't have this file
>Could you please share enableRDP.ps1 file ?
>Thank you
>Regards,
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
--
Media Bots

**Comment by ul0lw** [comment]
Thank you 
unfortunately it did not solve my problem
I am using VPS from contabo sever I install ubuntu 20.04 then I install windows server 2012 in KVN inside ubuntu 
I can access Ubuntu through VNC but I can't access windows server through RDP.
My IP starts with 164. but to access VNC they provides us with IP starts with 173.
I tried everything I don't believe it will work except using third party solution.

Thank you again for ur help. I hope u will have a good day.
