### ISSUE TITLE
vnc connection error

### ISSUE THREAD

**Issue by benybh** [mediabots/Linux-to-Windows-with-QEMU#5]
i have to use vps ubuntu 18.04 has run your cript but stuck in step connecting to vnc

**Comment by benybh** [comment]
<img width="545" alt="Capture" src="https://user-images.githubusercontent.com/6222861/59141115-a0c5d280-89d1-11e9-9be8-404a360a2150.PNG">

**Comment by benybh** [comment]
<img width="545" alt="Capture" src="https://user-images.githubusercontent.com/6222861/59141148-16ca3980-89d2-11e9-8073-820127fd83d2.PNG">

**Comment by mediabots** [comment]
Very sorry for the late reply!

I can see an error , 
- drive file=,

it should not be empty, some thing must be wrong.

Give me output/screenshot of following 3 commands separately:- 
df
fdisk -l
lsblk

So I can inspect the issue.
Also, which Web Hosting service are you using? URL please
ow much Disk space does it has?

looking forward
Regards

**Comment by boykuncute** [comment]
Thank you for your feedback. This is a snapshot of the above 3 commands
<img width="501" alt="Capture" src="https://user-images.githubusercontent.com/6087375/59728789-aa6af800-9265-11e9-91fa-72c83ae97ac9.PNG">
<img width="499" alt="Capture1" src="https://user-images.githubusercontent.com/6087375/59728790-aa6af800-9265-11e9-8efd-35d7a9e114cc.PNG">
<img width="500" alt="Capture2" src="https://user-images.githubusercontent.com/6087375/59728791-aa6af800-9265-11e9-92d0-cd18bc34bfd0.PNG">
<img width="493" alt="Capture3" src="https://user-images.githubusercontent.com/6087375/59728792-ab038e80-9265-11e9-8641-9f6a45caf788.PNG">

**Comment by mediabots** [comment]
that's weird
https://user-images.githubusercontent.com/6087375/59728790-aa6af800-9265-11e9-8efd-35d7a9e114cc.PNG
fdisk -l returns nothing!

which web hosting are you using? And which plan?

**Comment by boykuncute** [comment]
Notification hosting service like this
We currently don't support running Qemu, nor windows inside a VPS. Qemu has a dependency on KVM. We have not yet implemented KVM but it is on our roadmap. Once we make the announcement that KVM is available, than you should be able to run Qemu.

**Comment by mediabots** [comment]
Ah! as Script requirement said, KVM is mandatory in this case.
You can try VPS from scaleway.com or a Droplet from DigitalOcean.com
You can also try a server from https://oneprovider.com/dedicated-servers/1gbps .as per my knowledge they are selling cheapest server

Regards
